# Generated by Django 4.0.4 on 2022-05-18 10:54

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('footer', '0002_footerpagecarouse_footerpage_sub_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterPageOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=40, null=True)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('internal_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='footerpage',
            name='sub_title',
        ),
        migrations.DeleteModel(
            name='FooterPageCarouse',
        ),
        migrations.AddField(
            model_name='footerpageorder',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_order', to='footer.footerpage'),
        ),
    ]
