# Generated by Django 4.0.4 on 2022-05-18 08:25

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('headr', wagtail.blocks.StructBlock([('sub_title', wagtail.blocks.CharBlock(required=True)), ('page', wagtail.blocks.PageChooserBlock(required=False)), ('url', wagtail.blocks.URLBlock(required=False)), ('dropdown_item', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(required=False)), ('page', wagtail.blocks.PageChooserBlock(required=False)), ('page_url', wagtail.blocks.URLBlock(max_length=60, required=False))])))]))], use_json_field=None)),
            ],
            options={
                'verbose_name': 'Header Page',
                'verbose_name_plural': 'Header Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
