# Generated by Django 4.0.4 on 2022-05-18 11:28

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerpage',
            name='content',
            field=wagtail.fields.StreamField([('header', wagtail.blocks.StructBlock([('sub_title', wagtail.blocks.CharBlock(required=True)), ('page', wagtail.blocks.PageChooserBlock(required=False)), ('url', wagtail.blocks.URLBlock(required=False)), ('dropdown_item', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(required=False)), ('page', wagtail.blocks.PageChooserBlock(required=False)), ('page_url', wagtail.blocks.URLBlock(max_length=60, required=False))])))]))], use_json_field=None),
        ),
    ]
